// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a8595b93-ec54-4157-95f3-e43378011f01",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_SXFbVVPxB",
    "aws_user_pools_web_client_id": "rmu5daqnmea7mpb52ve7r993b"
};


export default awsmobile;
